# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fw6XJXP8-qA5rJ349OXSVEh5ZayBoUz3
"""



import pandas as pd
df = pd.read_csv('data/tweets/elon_musk_tweets.csv')
df.head()

from transformers import AutoTokenizer, AutoModelForSequenceClassification, pipeline

# Load FinBERT
tokenizer = AutoTokenizer.from_pretrained("ProsusAI/finbert")
model = AutoModelForSequenceClassification.from_pretrained("ProsusAI/finbert")

# Create sentiment analysis pipeline
finbert = pipeline("sentiment-analysis", model=model, tokenizer=tokenizer)

def directional_score(text):
    try:
        result = finbert(text[:512])[0]  # Truncate long tweets
        label = result["label"]
        score = result["score"]
        if label == "positive":
            return score
        elif label == "negative":
            return -score
        else:
            return 0
    except:
        return None

# Run sentiment analysis
df["sentiment_result"] = df["text"].apply(lambda x: finbert(x)[0])
df["sentiment"] = df["sentiment_result"].apply(lambda x: x['label'])
df["confidence"] = df["sentiment_result"].apply(lambda x: x['score'])
df["sentiment_score"] = df["text"].apply(directional_score)

# See sentiment distribution
print(df["sentiment"].value_counts())

# Save to new CSV
df.to_csv("tweets_with_sentiment.csv", index=False)

